/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Time = IDL.Int;
export const Album = IDL.Record({
  'id' : IDL.Text,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'createdTime' : Time,
  'mediaIds' : IDL.Vec(IDL.Text),
  'isHidden' : IDL.Bool,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const ImageFilter = IDL.Variant({
  'contrast' : IDL.Record({ 'level' : IDL.Float64 }),
  'blur' : IDL.Null,
  'none' : IDL.Null,
  'colorAdjustment' : IDL.Record({
    'red' : IDL.Int,
    'blue' : IDL.Int,
    'green' : IDL.Int,
  }),
  'brightness' : IDL.Record({ 'level' : IDL.Float64 }),
  'sepia' : IDL.Null,
  'grayscale' : IDL.Null,
});
export const PhotoEditing = IDL.Record({
  'filters' : IDL.Opt(IDL.Vec(ImageFilter)),
  'crop' : IDL.Opt(
    IDL.Record({
      'x' : IDL.Int,
      'y' : IDL.Int,
      'height' : IDL.Int,
      'width' : IDL.Int,
    })
  ),
  'rotate' : IDL.Opt(IDL.Float64),
});
export const MediaItem = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'originalBlob' : ExternalBlob,
  'editing' : IDL.Opt(PhotoEditing),
  'owner' : IDL.Principal,
  'size' : IDL.Nat,
  'description' : IDL.Text,
  'thumbnailBlob' : ExternalBlob,
  'mediaType' : IDL.Variant({ 'video' : IDL.Null, 'photo' : IDL.Null }),
  'isLocked' : IDL.Bool,
  'editedBlob' : IDL.Opt(ExternalBlob),
  'uploadTime' : Time,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const VaultSetting = IDL.Record({
  'pinAttempts' : IDL.Nat,
  'isVaultLocked' : IDL.Bool,
  'pinHash' : IDL.Opt(IDL.Text),
});
export const LibraryMetadata = IDL.Record({
  'albums' : IDL.Vec(Album),
  'mediaItems' : IDL.Vec(MediaItem),
  'vaultSetting' : IDL.Opt(VaultSetting),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAlbum' : IDL.Func([Album], [], []),
  'addMediaItem' : IDL.Func([MediaItem], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAlbum' : IDL.Func([IDL.Text], [IDL.Opt(Album)], ['query']),
  'getAllAlbums' : IDL.Func([], [IDL.Vec(Album)], ['query']),
  'getAllMedia' : IDL.Func([], [IDL.Vec(MediaItem)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLibraryMetadata' : IDL.Func([], [IDL.Opt(LibraryMetadata)], ['query']),
  'getMediaItem' : IDL.Func([IDL.Text], [IDL.Opt(MediaItem)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVaultStatus' : IDL.Func([], [IDL.Opt(VaultSetting)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'reorderAlbums' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setVaultPIN' : IDL.Func([IDL.Text], [], []),
  'unlockVault' : IDL.Func([IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Time = IDL.Int;
  const Album = IDL.Record({
    'id' : IDL.Text,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'createdTime' : Time,
    'mediaIds' : IDL.Vec(IDL.Text),
    'isHidden' : IDL.Bool,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const ImageFilter = IDL.Variant({
    'contrast' : IDL.Record({ 'level' : IDL.Float64 }),
    'blur' : IDL.Null,
    'none' : IDL.Null,
    'colorAdjustment' : IDL.Record({
      'red' : IDL.Int,
      'blue' : IDL.Int,
      'green' : IDL.Int,
    }),
    'brightness' : IDL.Record({ 'level' : IDL.Float64 }),
    'sepia' : IDL.Null,
    'grayscale' : IDL.Null,
  });
  const PhotoEditing = IDL.Record({
    'filters' : IDL.Opt(IDL.Vec(ImageFilter)),
    'crop' : IDL.Opt(
      IDL.Record({
        'x' : IDL.Int,
        'y' : IDL.Int,
        'height' : IDL.Int,
        'width' : IDL.Int,
      })
    ),
    'rotate' : IDL.Opt(IDL.Float64),
  });
  const MediaItem = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'originalBlob' : ExternalBlob,
    'editing' : IDL.Opt(PhotoEditing),
    'owner' : IDL.Principal,
    'size' : IDL.Nat,
    'description' : IDL.Text,
    'thumbnailBlob' : ExternalBlob,
    'mediaType' : IDL.Variant({ 'video' : IDL.Null, 'photo' : IDL.Null }),
    'isLocked' : IDL.Bool,
    'editedBlob' : IDL.Opt(ExternalBlob),
    'uploadTime' : Time,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const VaultSetting = IDL.Record({
    'pinAttempts' : IDL.Nat,
    'isVaultLocked' : IDL.Bool,
    'pinHash' : IDL.Opt(IDL.Text),
  });
  const LibraryMetadata = IDL.Record({
    'albums' : IDL.Vec(Album),
    'mediaItems' : IDL.Vec(MediaItem),
    'vaultSetting' : IDL.Opt(VaultSetting),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAlbum' : IDL.Func([Album], [], []),
    'addMediaItem' : IDL.Func([MediaItem], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAlbum' : IDL.Func([IDL.Text], [IDL.Opt(Album)], ['query']),
    'getAllAlbums' : IDL.Func([], [IDL.Vec(Album)], ['query']),
    'getAllMedia' : IDL.Func([], [IDL.Vec(MediaItem)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLibraryMetadata' : IDL.Func([], [IDL.Opt(LibraryMetadata)], ['query']),
    'getMediaItem' : IDL.Func([IDL.Text], [IDL.Opt(MediaItem)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVaultStatus' : IDL.Func([], [IDL.Opt(VaultSetting)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'reorderAlbums' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setVaultPIN' : IDL.Func([IDL.Text], [], []),
    'unlockVault' : IDL.Func([IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };