/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Album {
  'id' : string,
  'owner' : Principal,
  'name' : string,
  'createdTime' : Time,
  'mediaIds' : Array<string>,
  'isHidden' : boolean,
}
export type ExternalBlob = Uint8Array;
export type ImageFilter = { 'contrast' : { 'level' : number } } |
  { 'blur' : null } |
  { 'none' : null } |
  {
    'colorAdjustment' : { 'red' : bigint, 'blue' : bigint, 'green' : bigint }
  } |
  { 'brightness' : { 'level' : number } } |
  { 'sepia' : null } |
  { 'grayscale' : null };
export interface LibraryMetadata {
  'albums' : Array<Album>,
  'mediaItems' : Array<MediaItem>,
  'vaultSetting' : [] | [VaultSetting],
}
export interface MediaItem {
  'id' : string,
  'title' : string,
  'originalBlob' : ExternalBlob,
  'editing' : [] | [PhotoEditing],
  'owner' : Principal,
  'size' : bigint,
  'description' : string,
  'thumbnailBlob' : ExternalBlob,
  'mediaType' : { 'video' : null } |
    { 'photo' : null },
  'isLocked' : boolean,
  'editedBlob' : [] | [ExternalBlob],
  'uploadTime' : Time,
}
export interface PhotoEditing {
  'filters' : [] | [Array<ImageFilter>],
  'crop' : [] | [
    { 'x' : bigint, 'y' : bigint, 'height' : bigint, 'width' : bigint }
  ],
  'rotate' : [] | [number],
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VaultSetting {
  'pinAttempts' : bigint,
  'isVaultLocked' : boolean,
  'pinHash' : [] | [string],
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAlbum' : ActorMethod<[Album], undefined>,
  'addMediaItem' : ActorMethod<[MediaItem], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAlbum' : ActorMethod<[string], [] | [Album]>,
  'getAllAlbums' : ActorMethod<[], Array<Album>>,
  'getAllMedia' : ActorMethod<[], Array<MediaItem>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLibraryMetadata' : ActorMethod<[], [] | [LibraryMetadata]>,
  'getMediaItem' : ActorMethod<[string], [] | [MediaItem]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVaultStatus' : ActorMethod<[], [] | [VaultSetting]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'reorderAlbums' : ActorMethod<[Array<string>], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setVaultPIN' : ActorMethod<[string], undefined>,
  'unlockVault' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];