/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Album {
    id: string;
    owner: Principal;
    name: string;
    createdTime: Time;
    mediaIds: Array<string>;
    isHidden: boolean;
}
export interface VaultSetting {
    pinAttempts: bigint;
    isVaultLocked: boolean;
    pinHash?: string;
}
export type Time = bigint;
export interface PhotoEditing {
    filters?: Array<ImageFilter>;
    crop?: {
        x: bigint;
        y: bigint;
        height: bigint;
        width: bigint;
    };
    rotate?: number;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface LibraryMetadata {
    albums: Array<Album>;
    mediaItems: Array<MediaItem>;
    vaultSetting?: VaultSetting;
}
export type ImageFilter = {
    __kind__: "contrast";
    contrast: {
        level: number;
    };
} | {
    __kind__: "blur";
    blur: null;
} | {
    __kind__: "none";
    none: null;
} | {
    __kind__: "colorAdjustment";
    colorAdjustment: {
        red: bigint;
        blue: bigint;
        green: bigint;
    };
} | {
    __kind__: "brightness";
    brightness: {
        level: number;
    };
} | {
    __kind__: "sepia";
    sepia: null;
} | {
    __kind__: "grayscale";
    grayscale: null;
};
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface MediaItem {
    id: string;
    title: string;
    originalBlob: ExternalBlob;
    editing?: PhotoEditing;
    owner: Principal;
    size: bigint;
    description: string;
    thumbnailBlob: ExternalBlob;
    mediaType: Variant_video_photo;
    isLocked: boolean;
    editedBlob?: ExternalBlob;
    uploadTime: Time;
}
export interface UserProfile {
    name: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_video_photo {
    video = "video",
    photo = "photo"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addAlbum(album: Album): Promise<void>;
    addMediaItem(item: MediaItem): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getAlbum(id: string): Promise<Album | null>;
    getAllAlbums(): Promise<Array<Album>>;
    getAllMedia(): Promise<Array<MediaItem>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getLibraryMetadata(): Promise<LibraryMetadata | null>;
    getMediaItem(id: string): Promise<MediaItem | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getVaultStatus(): Promise<VaultSetting | null>;
    isCallerAdmin(): Promise<boolean>;
    reorderAlbums(newOrder: Array<string>): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setVaultPIN(pinHash: string): Promise<void>;
    unlockVault(pin: string): Promise<boolean>;
}
import type { Album as _Album, ExternalBlob as _ExternalBlob, ImageFilter as _ImageFilter, LibraryMetadata as _LibraryMetadata, MediaItem as _MediaItem, PhotoEditing as _PhotoEditing, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, VaultSetting as _VaultSetting, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addAlbum(arg0: Album): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAlbum(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAlbum(arg0);
            return result;
        }
    }
    async addMediaItem(arg0: MediaItem): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMediaItem(await to_candid_MediaItem_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMediaItem(await to_candid_MediaItem_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n17(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n17(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getAlbum(arg0: string): Promise<Album | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAlbum(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAlbum(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllAlbums(): Promise<Array<Album>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAlbums();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAlbums();
            return result;
        }
    }
    async getAllMedia(): Promise<Array<MediaItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMedia();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMedia();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLibraryMetadata(): Promise<LibraryMetadata | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLibraryMetadata();
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLibraryMetadata();
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMediaItem(arg0: string): Promise<MediaItem | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMediaItem(arg0);
                return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMediaItem(arg0);
            return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVaultStatus(): Promise<VaultSetting | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getVaultStatus();
                return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVaultStatus();
            return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async reorderAlbums(arg0: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.reorderAlbums(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reorderAlbums(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setVaultPIN(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setVaultPIN(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setVaultPIN(arg0);
            return result;
        }
    }
    async unlockVault(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.unlockVault(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unlockVault(arg0);
            return result;
        }
    }
}
async function from_candid_ExternalBlob_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_ImageFilter_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImageFilter): ImageFilter {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
async function from_candid_LibraryMetadata_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LibraryMetadata): Promise<LibraryMetadata> {
    return await from_candid_record_n40(_uploadFile, _downloadFile, value);
}
async function from_candid_MediaItem_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MediaItem): Promise<MediaItem> {
    return await from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_PhotoEditing_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PhotoEditing): PhotoEditing {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid_VaultSetting_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VaultSetting): VaultSetting {
    return from_candid_record_n43(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Album]): Album | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PhotoEditing]): PhotoEditing | null {
    return value.length === 0 ? null : from_candid_PhotoEditing_n25(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<_ImageFilter>]): Array<ImageFilter> | null {
    return value.length === 0 ? null : from_candid_vec_n28(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        x: bigint;
        y: bigint;
        height: bigint;
        width: bigint;
    }]): {
    x: bigint;
    y: bigint;
    height: bigint;
    width: bigint;
} | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n23(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_LibraryMetadata]): Promise<LibraryMetadata | null> {
    return value.length === 0 ? null : await from_candid_LibraryMetadata_n39(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_VaultSetting]): VaultSetting | null {
    return value.length === 0 ? null : from_candid_VaultSetting_n42(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MediaItem]): Promise<MediaItem | null> {
    return value.length === 0 ? null : await from_candid_MediaItem_n21(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    originalBlob: _ExternalBlob;
    editing: [] | [_PhotoEditing];
    owner: Principal;
    size: bigint;
    description: string;
    thumbnailBlob: _ExternalBlob;
    mediaType: {
        video: null;
    } | {
        photo: null;
    };
    isLocked: boolean;
    editedBlob: [] | [_ExternalBlob];
    uploadTime: _Time;
}): Promise<{
    id: string;
    title: string;
    originalBlob: ExternalBlob;
    editing?: PhotoEditing;
    owner: Principal;
    size: bigint;
    description: string;
    thumbnailBlob: ExternalBlob;
    mediaType: Variant_video_photo;
    isLocked: boolean;
    editedBlob?: ExternalBlob;
    uploadTime: Time;
}> {
    return {
        id: value.id,
        title: value.title,
        originalBlob: await from_candid_ExternalBlob_n23(_uploadFile, _downloadFile, value.originalBlob),
        editing: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.editing)),
        owner: value.owner,
        size: value.size,
        description: value.description,
        thumbnailBlob: await from_candid_ExternalBlob_n23(_uploadFile, _downloadFile, value.thumbnailBlob),
        mediaType: from_candid_variant_n33(_uploadFile, _downloadFile, value.mediaType),
        isLocked: value.isLocked,
        editedBlob: record_opt_to_undefined(await from_candid_opt_n34(_uploadFile, _downloadFile, value.editedBlob)),
        uploadTime: value.uploadTime
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    filters: [] | [Array<_ImageFilter>];
    crop: [] | [{
            x: bigint;
            y: bigint;
            height: bigint;
            width: bigint;
        }];
    rotate: [] | [number];
}): {
    filters?: Array<ImageFilter>;
    crop?: {
        x: bigint;
        y: bigint;
        height: bigint;
        width: bigint;
    };
    rotate?: number;
} {
    return {
        filters: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.filters)),
        crop: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.crop)),
        rotate: record_opt_to_undefined(from_candid_opt_n32(_uploadFile, _downloadFile, value.rotate))
    };
}
async function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    albums: Array<_Album>;
    mediaItems: Array<_MediaItem>;
    vaultSetting: [] | [_VaultSetting];
}): Promise<{
    albums: Array<Album>;
    mediaItems: Array<MediaItem>;
    vaultSetting?: VaultSetting;
}> {
    return {
        albums: value.albums,
        mediaItems: await from_candid_vec_n20(_uploadFile, _downloadFile, value.mediaItems),
        vaultSetting: record_opt_to_undefined(from_candid_opt_n41(_uploadFile, _downloadFile, value.vaultSetting))
    };
}
function from_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pinAttempts: bigint;
    isVaultLocked: boolean;
    pinHash: [] | [string];
}): {
    pinAttempts: bigint;
    isVaultLocked: boolean;
    pinHash?: string;
} {
    return {
        pinAttempts: value.pinAttempts,
        isVaultLocked: value.isVaultLocked,
        pinHash: record_opt_to_undefined(from_candid_opt_n44(_uploadFile, _downloadFile, value.pinHash))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    contrast: {
        level: number;
    };
} | {
    blur: null;
} | {
    none: null;
} | {
    colorAdjustment: {
        red: bigint;
        blue: bigint;
        green: bigint;
    };
} | {
    brightness: {
        level: number;
    };
} | {
    sepia: null;
} | {
    grayscale: null;
}): {
    __kind__: "contrast";
    contrast: {
        level: number;
    };
} | {
    __kind__: "blur";
    blur: null;
} | {
    __kind__: "none";
    none: null;
} | {
    __kind__: "colorAdjustment";
    colorAdjustment: {
        red: bigint;
        blue: bigint;
        green: bigint;
    };
} | {
    __kind__: "brightness";
    brightness: {
        level: number;
    };
} | {
    __kind__: "sepia";
    sepia: null;
} | {
    __kind__: "grayscale";
    grayscale: null;
} {
    return "contrast" in value ? {
        __kind__: "contrast",
        contrast: value.contrast
    } : "blur" in value ? {
        __kind__: "blur",
        blur: value.blur
    } : "none" in value ? {
        __kind__: "none",
        none: value.none
    } : "colorAdjustment" in value ? {
        __kind__: "colorAdjustment",
        colorAdjustment: value.colorAdjustment
    } : "brightness" in value ? {
        __kind__: "brightness",
        brightness: value.brightness
    } : "sepia" in value ? {
        __kind__: "sepia",
        sepia: value.sepia
    } : "grayscale" in value ? {
        __kind__: "grayscale",
        grayscale: value.grayscale
    } : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    video: null;
} | {
    photo: null;
}): Variant_video_photo {
    return "video" in value ? Variant_video_photo.video : "photo" in value ? Variant_video_photo.photo : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MediaItem>): Promise<Array<MediaItem>> {
    return await Promise.all(value.map(async (x)=>await from_candid_MediaItem_n21(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ImageFilter>): Array<ImageFilter> {
    return value.map((x)=>from_candid_ImageFilter_n29(_uploadFile, _downloadFile, x));
}
async function to_candid_ExternalBlob_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_ImageFilter_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ImageFilter): _ImageFilter {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
async function to_candid_MediaItem_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MediaItem): Promise<_MediaItem> {
    return await to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_PhotoEditing_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PhotoEditing): _PhotoEditing {
    return to_candid_record_n12(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    filters?: Array<ImageFilter>;
    crop?: {
        x: bigint;
        y: bigint;
        height: bigint;
        width: bigint;
    };
    rotate?: number;
}): {
    filters: [] | [Array<_ImageFilter>];
    crop: [] | [{
            x: bigint;
            y: bigint;
            height: bigint;
            width: bigint;
        }];
    rotate: [] | [number];
} {
    return {
        filters: value.filters ? candid_some(to_candid_vec_n13(_uploadFile, _downloadFile, value.filters)) : candid_none(),
        crop: value.crop ? candid_some(value.crop) : candid_none(),
        rotate: value.rotate ? candid_some(value.rotate) : candid_none()
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    originalBlob: ExternalBlob;
    editing?: PhotoEditing;
    owner: Principal;
    size: bigint;
    description: string;
    thumbnailBlob: ExternalBlob;
    mediaType: Variant_video_photo;
    isLocked: boolean;
    editedBlob?: ExternalBlob;
    uploadTime: Time;
}): Promise<{
    id: string;
    title: string;
    originalBlob: _ExternalBlob;
    editing: [] | [_PhotoEditing];
    owner: Principal;
    size: bigint;
    description: string;
    thumbnailBlob: _ExternalBlob;
    mediaType: {
        video: null;
    } | {
        photo: null;
    };
    isLocked: boolean;
    editedBlob: [] | [_ExternalBlob];
    uploadTime: _Time;
}> {
    return {
        id: value.id,
        title: value.title,
        originalBlob: await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.originalBlob),
        editing: value.editing ? candid_some(to_candid_PhotoEditing_n11(_uploadFile, _downloadFile, value.editing)) : candid_none(),
        owner: value.owner,
        size: value.size,
        description: value.description,
        thumbnailBlob: await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.thumbnailBlob),
        mediaType: to_candid_variant_n16(_uploadFile, _downloadFile, value.mediaType),
        isLocked: value.isLocked,
        editedBlob: value.editedBlob ? candid_some(await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.editedBlob)) : candid_none(),
        uploadTime: value.uploadTime
    };
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "contrast";
    contrast: {
        level: number;
    };
} | {
    __kind__: "blur";
    blur: null;
} | {
    __kind__: "none";
    none: null;
} | {
    __kind__: "colorAdjustment";
    colorAdjustment: {
        red: bigint;
        blue: bigint;
        green: bigint;
    };
} | {
    __kind__: "brightness";
    brightness: {
        level: number;
    };
} | {
    __kind__: "sepia";
    sepia: null;
} | {
    __kind__: "grayscale";
    grayscale: null;
}): {
    contrast: {
        level: number;
    };
} | {
    blur: null;
} | {
    none: null;
} | {
    colorAdjustment: {
        red: bigint;
        blue: bigint;
        green: bigint;
    };
} | {
    brightness: {
        level: number;
    };
} | {
    sepia: null;
} | {
    grayscale: null;
} {
    return value.__kind__ === "contrast" ? {
        contrast: value.contrast
    } : value.__kind__ === "blur" ? {
        blur: value.blur
    } : value.__kind__ === "none" ? {
        none: value.none
    } : value.__kind__ === "colorAdjustment" ? {
        colorAdjustment: value.colorAdjustment
    } : value.__kind__ === "brightness" ? {
        brightness: value.brightness
    } : value.__kind__ === "sepia" ? {
        sepia: value.sepia
    } : value.__kind__ === "grayscale" ? {
        grayscale: value.grayscale
    } : value;
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_video_photo): {
    video: null;
} | {
    photo: null;
} {
    return value == Variant_video_photo.video ? {
        video: null
    } : value == Variant_video_photo.photo ? {
        photo: null
    } : value;
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ImageFilter>): Array<_ImageFilter> {
    return value.map((x)=>to_candid_ImageFilter_n14(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
